# Generated by Django 3.0.3 on 2020-03-03 22:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('codigo',models.CharField(verbose_name='codigo', max_length=20)),
                ('longitud',models.IntegerField(verbose_name='longitud')),
                ('latitud',models.IntegerField(verbose_name='latitud')),
                ('terreno',models.CharField(verbose_name='terreno',max_length=20)),
                ('area', models.IntegerField(verbose_name='area')),



            ],
        ),
    ]
