# Generated by Django 3.0.5 on 2020-05-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='area',
            field=models.IntegerField(default=1, verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='codigo',
            field=models.CharField(default='20181400', max_length=20, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='id',
            field=models.UUIDField(default=int, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='measure',
            name='latitud',
            field=models.IntegerField(default=1, verbose_name='latitud'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='longitud',
            field=models.IntegerField(default=1, verbose_name='longitud'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='terreno',
            field=models.CharField(default='Planicie', max_length=20, verbose_name='terreno'),
        ),
    ]
